/*

 CAKE_ICON.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 38 to 41

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define cake_iconBank 0

/* Super Gameboy palette 0 */
#define cake_iconSGBPal0c0 6076
#define cake_iconSGBPal0c1 8935
#define cake_iconSGBPal0c2 6596
#define cake_iconSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define cake_iconSGBPal1c0 6076
#define cake_iconSGBPal1c1 8935
#define cake_iconSGBPal1c2 6596
#define cake_iconSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define cake_iconSGBPal2c0 6076
#define cake_iconSGBPal2c1 8935
#define cake_iconSGBPal2c2 6596
#define cake_iconSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define cake_iconSGBPal3c0 6076
#define cake_iconSGBPal3c1 8935
#define cake_iconSGBPal3c2 6596
#define cake_iconSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define cake_iconCGBPal0c0 32767
#define cake_iconCGBPal0c1 26111
#define cake_iconCGBPal0c2 20831
#define cake_iconCGBPal0c3 15551

/* Gameboy Color palette 1 */
#define cake_iconCGBPal1c0 4228
#define cake_iconCGBPal1c1 26111
#define cake_iconCGBPal1c2 20831
#define cake_iconCGBPal1c3 15551

/* Gameboy Color palette 2 */
#define cake_iconCGBPal2c0 6076
#define cake_iconCGBPal2c1 8935
#define cake_iconCGBPal2c2 6596
#define cake_iconCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define cake_iconCGBPal3c0 6076
#define cake_iconCGBPal3c1 8935
#define cake_iconCGBPal3c2 6596
#define cake_iconCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define cake_iconCGBPal4c0 6076
#define cake_iconCGBPal4c1 8935
#define cake_iconCGBPal4c2 6596
#define cake_iconCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define cake_iconCGBPal5c0 6076
#define cake_iconCGBPal5c1 8935
#define cake_iconCGBPal5c2 6596
#define cake_iconCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define cake_iconCGBPal6c0 32767
#define cake_iconCGBPal6c1 26111
#define cake_iconCGBPal6c2 20831
#define cake_iconCGBPal6c3 15551

/* Gameboy Color palette 7 */
#define cake_iconCGBPal7c0 6076
#define cake_iconCGBPal7c1 8935
#define cake_iconCGBPal7c2 6596
#define cake_iconCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char cake_icon[];

/* End of CAKE_ICON.H */
