/*

 CAKE_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 2
   Tile set      : font1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 1
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define cake_mapWidth 2
#define cake_mapHeight 2
#define cake_mapBank 0

#define cake_map cake_mapPLN0
const unsigned char cake_mapPLN0[] =
{
  0x27,0x28,0x29,0x2A
};

const unsigned char cake_mapPLN1[] =
{
  0x06,0x00,0x00,0x00
};

/* End of CAKE_MAP.C */
