/*

 CHR_TILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 79

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define chr_tilesetBank 0

/* Super Gameboy palette 0 */
#define chr_tilesetSGBPal0c0 6076
#define chr_tilesetSGBPal0c1 8935
#define chr_tilesetSGBPal0c2 6596
#define chr_tilesetSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define chr_tilesetSGBPal1c0 6076
#define chr_tilesetSGBPal1c1 8935
#define chr_tilesetSGBPal1c2 6596
#define chr_tilesetSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define chr_tilesetSGBPal2c0 6076
#define chr_tilesetSGBPal2c1 8935
#define chr_tilesetSGBPal2c2 6596
#define chr_tilesetSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define chr_tilesetSGBPal3c0 6076
#define chr_tilesetSGBPal3c1 8935
#define chr_tilesetSGBPal3c2 6596
#define chr_tilesetSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define chr_tilesetCGBPal0c0 32767
#define chr_tilesetCGBPal0c1 26111
#define chr_tilesetCGBPal0c2 20831
#define chr_tilesetCGBPal0c3 15551

/* Gameboy Color palette 1 */
#define chr_tilesetCGBPal1c0 4228
#define chr_tilesetCGBPal1c1 26111
#define chr_tilesetCGBPal1c2 20831
#define chr_tilesetCGBPal1c3 15551

/* Gameboy Color palette 2 */
#define chr_tilesetCGBPal2c0 32767
#define chr_tilesetCGBPal2c1 15761
#define chr_tilesetCGBPal2c2 7401
#define chr_tilesetCGBPal2c3 3172

/* Gameboy Color palette 3 */
#define chr_tilesetCGBPal3c0 32767
#define chr_tilesetCGBPal3c1 25368
#define chr_tilesetCGBPal3c2 16912
#define chr_tilesetCGBPal3c3 8456

/* Gameboy Color palette 4 */
#define chr_tilesetCGBPal4c0 32767
#define chr_tilesetCGBPal4c1 31698
#define chr_tilesetCGBPal4c2 32206
#define chr_tilesetCGBPal4c3 20810

/* Gameboy Color palette 5 */
#define chr_tilesetCGBPal5c0 32767
#define chr_tilesetCGBPal5c1 10910
#define chr_tilesetCGBPal5c2 7637
#define chr_tilesetCGBPal5c3 4432

/* Gameboy Color palette 6 */
#define chr_tilesetCGBPal6c0 32767
#define chr_tilesetCGBPal6c1 26111
#define chr_tilesetCGBPal6c2 20831
#define chr_tilesetCGBPal6c3 15551

/* Gameboy Color palette 7 */
#define chr_tilesetCGBPal7c0 6076
#define chr_tilesetCGBPal7c1 8935
#define chr_tilesetCGBPal7c2 6596
#define chr_tilesetCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char chr_tileset[];
#define chr_tilesetLen 80

/* End of CHR_TILESET.H */
