/*

 SPR_FIREBALL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spr_fireballBank 0

/* Super Gameboy palette 0 */
#define spr_fireballSGBPal0c0 6076
#define spr_fireballSGBPal0c1 8935
#define spr_fireballSGBPal0c2 6596
#define spr_fireballSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spr_fireballSGBPal1c0 6076
#define spr_fireballSGBPal1c1 8935
#define spr_fireballSGBPal1c2 6596
#define spr_fireballSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spr_fireballSGBPal2c0 6076
#define spr_fireballSGBPal2c1 8935
#define spr_fireballSGBPal2c2 6596
#define spr_fireballSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spr_fireballSGBPal3c0 6076
#define spr_fireballSGBPal3c1 8935
#define spr_fireballSGBPal3c2 6596
#define spr_fireballSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spr_fireballCGBPal0c0 32767
#define spr_fireballCGBPal0c1 4895
#define spr_fireballCGBPal0c2 8472
#define spr_fireballCGBPal0c3 8456

/* Gameboy Color palette 1 */
#define spr_fireballCGBPal1c0 32767
#define spr_fireballCGBPal1c1 4895
#define spr_fireballCGBPal1c2 31
#define spr_fireballCGBPal1c3 2085

/* Gameboy Color palette 2 */
#define spr_fireballCGBPal2c0 6076
#define spr_fireballCGBPal2c1 8935
#define spr_fireballCGBPal2c2 6596
#define spr_fireballCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define spr_fireballCGBPal3c0 6076
#define spr_fireballCGBPal3c1 8935
#define spr_fireballCGBPal3c2 6596
#define spr_fireballCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define spr_fireballCGBPal4c0 6076
#define spr_fireballCGBPal4c1 8935
#define spr_fireballCGBPal4c2 6596
#define spr_fireballCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spr_fireballCGBPal5c0 6076
#define spr_fireballCGBPal5c1 8935
#define spr_fireballCGBPal5c2 6596
#define spr_fireballCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spr_fireballCGBPal6c0 6076
#define spr_fireballCGBPal6c1 8935
#define spr_fireballCGBPal6c2 6596
#define spr_fireballCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spr_fireballCGBPal7c0 6076
#define spr_fireballCGBPal7c1 8935
#define spr_fireballCGBPal7c2 6596
#define spr_fireballCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char spr_fireball[];
#define spr_fireballLen 2

/* End of SPR_FIREBALL.H */
