/*

 SPR_FLOWER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spr_flowerBank 0

/* Super Gameboy palette 0 */
#define spr_flowerSGBPal0c0 6076
#define spr_flowerSGBPal0c1 8935
#define spr_flowerSGBPal0c2 6596
#define spr_flowerSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spr_flowerSGBPal1c0 6076
#define spr_flowerSGBPal1c1 8935
#define spr_flowerSGBPal1c2 6596
#define spr_flowerSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spr_flowerSGBPal2c0 6076
#define spr_flowerSGBPal2c1 8935
#define spr_flowerSGBPal2c2 6596
#define spr_flowerSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spr_flowerSGBPal3c0 6076
#define spr_flowerSGBPal3c1 8935
#define spr_flowerSGBPal3c2 6596
#define spr_flowerSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spr_flowerCGBPal0c0 32767
#define spr_flowerCGBPal0c1 6137
#define spr_flowerCGBPal0c2 5096
#define spr_flowerCGBPal0c3 517

/* Gameboy Color palette 1 */
#define spr_flowerCGBPal1c0 32767
#define spr_flowerCGBPal1c1 32265
#define spr_flowerCGBPal1c2 5096
#define spr_flowerCGBPal1c3 517

/* Gameboy Color palette 2 */
#define spr_flowerCGBPal2c0 32767
#define spr_flowerCGBPal2c1 31744
#define spr_flowerCGBPal2c2 3042
#define spr_flowerCGBPal2c3 96

/* Gameboy Color palette 3 */
#define spr_flowerCGBPal3c0 32767
#define spr_flowerCGBPal3c1 31744
#define spr_flowerCGBPal3c2 3042
#define spr_flowerCGBPal3c3 96

/* Gameboy Color palette 4 */
#define spr_flowerCGBPal4c0 32767
#define spr_flowerCGBPal4c1 31744
#define spr_flowerCGBPal4c2 3042
#define spr_flowerCGBPal4c3 96

/* Gameboy Color palette 5 */
#define spr_flowerCGBPal5c0 32767
#define spr_flowerCGBPal5c1 31744
#define spr_flowerCGBPal5c2 3042
#define spr_flowerCGBPal5c3 96

/* Gameboy Color palette 6 */
#define spr_flowerCGBPal6c0 32767
#define spr_flowerCGBPal6c1 31744
#define spr_flowerCGBPal6c2 3042
#define spr_flowerCGBPal6c3 96

/* Gameboy Color palette 7 */
#define spr_flowerCGBPal7c0 32767
#define spr_flowerCGBPal7c1 31744
#define spr_flowerCGBPal7c2 3042
#define spr_flowerCGBPal7c3 96
/* Start of tile array. */
extern unsigned char spr_flower[];
#define spr_flowerLen 12

/* End of SPR_FLOWER.H */
