/*

 SPR_BEAR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spr_bearBank 0

/* Super Gameboy palette 0 */
#define spr_bearSGBPal0c0 6076
#define spr_bearSGBPal0c1 8935
#define spr_bearSGBPal0c2 6596
#define spr_bearSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spr_bearSGBPal1c0 6076
#define spr_bearSGBPal1c1 8935
#define spr_bearSGBPal1c2 6596
#define spr_bearSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spr_bearSGBPal2c0 6076
#define spr_bearSGBPal2c1 8935
#define spr_bearSGBPal2c2 6596
#define spr_bearSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spr_bearSGBPal3c0 6076
#define spr_bearSGBPal3c1 8935
#define spr_bearSGBPal3c2 6596
#define spr_bearSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spr_bearCGBPal0c0 32767
#define spr_bearCGBPal0c1 6975
#define spr_bearCGBPal0c2 1160
#define spr_bearCGBPal0c3 8456

/* Gameboy Color palette 1 */
#define spr_bearCGBPal1c0 32767
#define spr_bearCGBPal1c1 6975
#define spr_bearCGBPal1c2 1359
#define spr_bearCGBPal1c3 200

/* Gameboy Color palette 2 */
#define spr_bearCGBPal2c0 6076
#define spr_bearCGBPal2c1 8935
#define spr_bearCGBPal2c2 6596
#define spr_bearCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define spr_bearCGBPal3c0 6076
#define spr_bearCGBPal3c1 8935
#define spr_bearCGBPal3c2 6596
#define spr_bearCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define spr_bearCGBPal4c0 6076
#define spr_bearCGBPal4c1 8935
#define spr_bearCGBPal4c2 6596
#define spr_bearCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spr_bearCGBPal5c0 6076
#define spr_bearCGBPal5c1 8935
#define spr_bearCGBPal5c2 6596
#define spr_bearCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spr_bearCGBPal6c0 6076
#define spr_bearCGBPal6c1 8935
#define spr_bearCGBPal6c2 6596
#define spr_bearCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spr_bearCGBPal7c0 6076
#define spr_bearCGBPal7c1 8935
#define spr_bearCGBPal7c2 6596
#define spr_bearCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char spr_bear[];
#define spr_bearLen 12

/* End of SPR_BEAR.H */
