/*

 SPR_PRINCESS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spr_princessBank 0

/* Super Gameboy palette 0 */
#define spr_princessSGBPal0c0 6076
#define spr_princessSGBPal0c1 8935
#define spr_princessSGBPal0c2 6596
#define spr_princessSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spr_princessSGBPal1c0 6076
#define spr_princessSGBPal1c1 8935
#define spr_princessSGBPal1c2 6596
#define spr_princessSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spr_princessSGBPal2c0 6076
#define spr_princessSGBPal2c1 8935
#define spr_princessSGBPal2c2 6596
#define spr_princessSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spr_princessSGBPal3c0 6076
#define spr_princessSGBPal3c1 8935
#define spr_princessSGBPal3c2 6596
#define spr_princessSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spr_princessCGBPal0c0 32767
#define spr_princessCGBPal0c1 8991
#define spr_princessCGBPal0c2 8472
#define spr_princessCGBPal0c3 8456

/* Gameboy Color palette 1 */
#define spr_princessCGBPal1c0 32767
#define spr_princessCGBPal1c1 8991
#define spr_princessCGBPal1c2 12511
#define spr_princessCGBPal1c3 12328

/* Gameboy Color palette 2 */
#define spr_princessCGBPal2c0 6076
#define spr_princessCGBPal2c1 8935
#define spr_princessCGBPal2c2 6596
#define spr_princessCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define spr_princessCGBPal3c0 6076
#define spr_princessCGBPal3c1 8935
#define spr_princessCGBPal3c2 6596
#define spr_princessCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define spr_princessCGBPal4c0 6076
#define spr_princessCGBPal4c1 8935
#define spr_princessCGBPal4c2 6596
#define spr_princessCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spr_princessCGBPal5c0 6076
#define spr_princessCGBPal5c1 8935
#define spr_princessCGBPal5c2 6596
#define spr_princessCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spr_princessCGBPal6c0 6076
#define spr_princessCGBPal6c1 8935
#define spr_princessCGBPal6c2 6596
#define spr_princessCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spr_princessCGBPal7c0 6076
#define spr_princessCGBPal7c1 8935
#define spr_princessCGBPal7c2 6596
#define spr_princessCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char spr_princess[];
#define spr_princessLen 24

/* End of SPR_PRINCESS.H */
