/*

 SPR_BUTT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spr_buttBank 0

/* Super Gameboy palette 0 */
#define spr_buttSGBPal0c0 6076
#define spr_buttSGBPal0c1 8935
#define spr_buttSGBPal0c2 6596
#define spr_buttSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spr_buttSGBPal1c0 6076
#define spr_buttSGBPal1c1 8935
#define spr_buttSGBPal1c2 6596
#define spr_buttSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spr_buttSGBPal2c0 6076
#define spr_buttSGBPal2c1 8935
#define spr_buttSGBPal2c2 6596
#define spr_buttSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spr_buttSGBPal3c0 6076
#define spr_buttSGBPal3c1 8935
#define spr_buttSGBPal3c2 6596
#define spr_buttSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spr_buttCGBPal0c0 28446
#define spr_buttCGBPal0c1 381
#define spr_buttCGBPal0c2 32069
#define spr_buttCGBPal0c3 2177

/* Gameboy Color palette 1 */
#define spr_buttCGBPal1c0 32767
#define spr_buttCGBPal1c1 8456
#define spr_buttCGBPal1c2 3487
#define spr_buttCGBPal1c3 5154

/* Gameboy Color palette 2 */
#define spr_buttCGBPal2c0 6076
#define spr_buttCGBPal2c1 8935
#define spr_buttCGBPal2c2 6596
#define spr_buttCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define spr_buttCGBPal3c0 6076
#define spr_buttCGBPal3c1 8935
#define spr_buttCGBPal3c2 6596
#define spr_buttCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define spr_buttCGBPal4c0 6076
#define spr_buttCGBPal4c1 8935
#define spr_buttCGBPal4c2 6596
#define spr_buttCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spr_buttCGBPal5c0 6076
#define spr_buttCGBPal5c1 8935
#define spr_buttCGBPal5c2 6596
#define spr_buttCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spr_buttCGBPal6c0 6076
#define spr_buttCGBPal6c1 8935
#define spr_buttCGBPal6c2 6596
#define spr_buttCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spr_buttCGBPal7c0 6076
#define spr_buttCGBPal7c1 8935
#define spr_buttCGBPal7c2 6596
#define spr_buttCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char spr_butt[];
#define spr_buttLen 8

/* End of SPR_BUTT.H */
