/*

 SPR_FLAME.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spr_flameBank 0

/* Super Gameboy palette 0 */
#define spr_flameSGBPal0c0 6076
#define spr_flameSGBPal0c1 8935
#define spr_flameSGBPal0c2 6596
#define spr_flameSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spr_flameSGBPal1c0 6076
#define spr_flameSGBPal1c1 8935
#define spr_flameSGBPal1c2 6596
#define spr_flameSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spr_flameSGBPal2c0 6076
#define spr_flameSGBPal2c1 8935
#define spr_flameSGBPal2c2 6596
#define spr_flameSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spr_flameSGBPal3c0 6076
#define spr_flameSGBPal3c1 8935
#define spr_flameSGBPal3c2 6596
#define spr_flameSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spr_flameCGBPal0c0 32767
#define spr_flameCGBPal0c1 4895
#define spr_flameCGBPal0c2 6424
#define spr_flameCGBPal0c3 3216

/* Gameboy Color palette 1 */
#define spr_flameCGBPal1c0 32767
#define spr_flameCGBPal1c1 4895
#define spr_flameCGBPal1c2 31
#define spr_flameCGBPal1c3 2085

/* Gameboy Color palette 2 */
#define spr_flameCGBPal2c0 32767
#define spr_flameCGBPal2c1 4895
#define spr_flameCGBPal2c2 31
#define spr_flameCGBPal2c3 2085

/* Gameboy Color palette 3 */
#define spr_flameCGBPal3c0 32767
#define spr_flameCGBPal3c1 4895
#define spr_flameCGBPal3c2 8472
#define spr_flameCGBPal3c3 8456

/* Gameboy Color palette 4 */
#define spr_flameCGBPal4c0 6076
#define spr_flameCGBPal4c1 8935
#define spr_flameCGBPal4c2 6596
#define spr_flameCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spr_flameCGBPal5c0 6076
#define spr_flameCGBPal5c1 8935
#define spr_flameCGBPal5c2 6596
#define spr_flameCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spr_flameCGBPal6c0 6076
#define spr_flameCGBPal6c1 8935
#define spr_flameCGBPal6c2 6596
#define spr_flameCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spr_flameCGBPal7c0 6076
#define spr_flameCGBPal7c1 8935
#define spr_flameCGBPal7c2 6596
#define spr_flameCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char spr_flame[];
#define spr_flameLen 24

/* End of SPR_FLAME.H */
