/*

 LV0.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 17
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv0Width 20
#define lv0Height 17
#define lv0Bank 0

#define lv0 lv0PLN0
extern unsigned char lv0PLN0[];
extern unsigned char lv0PLN1[];

/* End of LV0.H */
