/*

 LV10.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 31 x 17
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv10Width 31
#define lv10Height 17
#define lv10Bank 0

#define lv10 lv10PLN0
extern unsigned char lv10PLN0[];
extern unsigned char lv10PLN1[];

/* End of LV10.H */
