/*

 LV11.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv11Width 20
#define lv11Height 32
#define lv11Bank 0

#define lv11 lv11PLN0
extern unsigned char lv11PLN0[];
extern unsigned char lv11PLN1[];

/* End of LV11.H */
