/*

 LV12.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 17
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv12Width 30
#define lv12Height 17
#define lv12Bank 0

#define lv12 lv12PLN0
extern unsigned char lv12PLN0[];
extern unsigned char lv12PLN1[];

/* End of LV12.H */
