/*

 LV20.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 17
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv20Width 20
#define lv20Height 17
#define lv20Bank 0

#define lv20 lv20PLN0
extern unsigned char lv20PLN0[];
extern unsigned char lv20PLN1[];

/* End of LV20.H */
