/*

 LV21.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 17
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv21Width 30
#define lv21Height 17
#define lv21Bank 0

#define lv21 lv21PLN0
extern unsigned char lv21PLN0[];
extern unsigned char lv21PLN1[];

/* End of LV21.H */
