/*

 LV24.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 24
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv24Width 30
#define lv24Height 24
#define lv24Bank 0

#define lv24 lv24PLN0
extern unsigned char lv24PLN0[];
extern unsigned char lv24PLN1[];

/* End of LV24.H */
