/*

 LV3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 31
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv3Width 20
#define lv3Height 31
#define lv3Bank 0

#define lv3 lv3PLN0
extern unsigned char lv3PLN0[];
extern unsigned char lv3PLN1[];

/* End of LV3.H */
