/*

 LV4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 17
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv4Width 20
#define lv4Height 17
#define lv4Bank 0

#define lv4 lv4PLN0
extern unsigned char lv4PLN0[];
extern unsigned char lv4PLN1[];

/* End of LV4.H */
