/*

 LV5.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 17
   Tile set      : ..\tiles3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lv5Width 20
#define lv5Height 17
#define lv5Bank 0

#define lv5 lv5PLN0
extern unsigned char lv5PLN0[];
extern unsigned char lv5PLN1[];

/* End of LV5.H */
