/*

 MAP_OSD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : osd.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_osdWidth 20
#define map_osdHeight 1
#define map_osdBank 0

#define map_osd map_osdPLN0
extern unsigned char map_osdPLN0[];
extern unsigned char map_osdPLN1[];

/* End of MAP_OSD.H */
