    dw __graphic00
    dw __graphic01
    dw __graphic02
    dw __graphic03
    dw __graphic04
    dw __graphic05
;        ..X XXX 
;        .. X X  
;        ..X XXX 
;        ..X     
;        ..X XXXX
;        ..X XXXX
;        ...X XXX
;        ...XX   
;        ..X     
;        .X X    
;        X XX    
;        X XXX   
;        X XXXX  
;        X XXXXX 
;        .X  XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ...X    
;        ....XXXX
__graphic00:
    db 023h
    db 0c0h
    db 011h
    db 0c0h
    db 02bh
    db 0c0h
    db 011h
    db 0c0h
    db 01fh
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0e0h
    db 008h
    db 0e0h
    db 007h
    db 0c0h
    db 01fh
    db 080h
    db 02fh
    db 000h
    db 04fh
    db 000h
    db 047h
    db 000h
    db 043h
    db 000h
    db 041h
    db 080h
    db 030h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0e0h
    db 00fh
    db 0f0h
    db 000h
    db 0ffh
__graphic01:
    db 024h
    db 003h
    db 088h
    db 003h
    db 0d4h
    db 003h
    db 088h
    db 003h
    db 0f8h
    db 003h
    db 008h
    db 003h
    db 008h
    db 007h
    db 010h
    db 007h
    db 0e0h
    db 003h
    db 0f8h
    db 001h
    db 0f4h
    db 000h
    db 0f2h
    db 000h
    db 0e2h
    db 000h
    db 0c2h
    db 000h
    db 082h
    db 001h
    db 00ch
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 007h
    db 0f0h
    db 00fh
    db 000h
    db 0ffh
;        ....X..X
;        ...X XX 
;        ....    
;        .... XXX
;        ....X XX
;        ....XX  
;        ..XX    
;        ..X X   
;        .. XXX  
;        .. XXXX 
;        ..X  XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ....X   
;        .....XXX
__graphic02:
    db 033h
    db 0f6h
    db 000h
    db 0e0h
    db 009h
    db 0f0h
    db 00fh
    db 0f0h
    db 008h
    db 0f0h
    db 004h
    db 0f0h
    db 003h
    db 0c0h
    db 00fh
    db 0c0h
    db 017h
    db 0c0h
    db 023h
    db 0c0h
    db 021h
    db 0c0h
    db 018h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0f0h
    db 007h
    db 0f8h
    db 000h
    db 0ffh
__graphic03:
    db 034h
    db 06fh
    db 000h
    db 007h
    db 090h
    db 00fh
    db 0f0h
    db 00fh
    db 010h
    db 00fh
    db 020h
    db 00fh
    db 0c0h
    db 003h
    db 0f0h
    db 003h
    db 0e8h
    db 003h
    db 0c4h
    db 003h
    db 084h
    db 003h
    db 018h
    db 007h
    db 010h
    db 007h
    db 010h
    db 007h
    db 010h
    db 007h
    db 010h
    db 007h
    db 010h
    db 00fh
    db 0e0h
    db 01fh
    db 000h
    db 0ffh
;        ....X X 
;        ....X   
;        ....X XX
;        .....X X
;        .....X  
;        ....X X 
;        ....X XX
;        ....X XX
;        .....X  
;        ......XX
__graphic04:
    db 053h
    db 0f0h
    db 005h
    db 0f0h
    db 007h
    db 0f0h
    db 004h
    db 0f8h
    db 002h
    db 0f8h
    db 003h
    db 0f0h
    db 005h
    db 0f0h
    db 004h
    db 0f0h
    db 004h
    db 0f8h
    db 003h
    db 0fch
    db 000h
    db 0ffh
__graphic05:
    db 054h
    db 00fh
    db 0a0h
    db 00fh
    db 0e0h
    db 00fh
    db 020h
    db 01fh
    db 040h
    db 01fh
    db 0c0h
    db 00fh
    db 0a0h
    db 00fh
    db 020h
    db 00fh
    db 020h
    db 01fh
    db 0c0h
    db 03fh
    db 000h
    db 0ffh
; 220
